version: "3.9"

services:
  big-data-frontend:
    container_name: frontend
    build: ./src/frontend
    image: dhbw-big-data-frontend:latest
    ports:
      - "3000:3000"
    restart: always

  big-data-hadoop:
    container_name: hadoop
    image: marcelmittelstaedt/spark_base:latest
    ports:
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8088:8088"
      - "8888:8888"
      - "9000:9000"
      - "9864:9864"
      - "9870:9870"
      - "10000:10000"
    restart: always


  big-data-airflow:
    container_name: airflow
    build: ./src/airflow
    image: dhbw-big-data-airflow:latest
    ports:
      - "8080:8080"
    restart: always

  big-data-mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/mongodb
      - ./src/mongodb/init.js:/docker-entrypoint-initdb.d/init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
      MONGO_INITDB_DATABASE: dhbw-big-data-mongodb

  big-data-mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: big-data-mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'false'
      ME_CONFIG_MONGODB_AUTH_DATABASE: dhbw-big-data-mongodb
      ME_CONFIG_MONGODB_AUTH_USERNAME: dev
      ME_CONFIG_MONGODB_AUTH_PASSWORD: dev
    depends_on:
      - big-data-mongodb

volumes:
  webserver:
  mongodb:
